repos:
    - repo: local
      hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        language_version: python3.7
        args: [--line-length=120]
    - repo: local
      hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: [--ignore-missing-imports, --namespace-packages, --show-error-codes, --pretty]
    - repo: local
      hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        args: ["--profile", "black", "--filter-files"]
    - repo: local
      hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: [--max-line-length=120, --docstring-convention=numpy, "--ignore=D100,D104,W503,W605,E712,E731,E203"]
# D100 requires all Python files (modules) to have a "public" docstring even if all functions within have a docstring.
# # D104 requires __init__ files to have a docstring
# # W503 requires no binary operators just after a line feed, but that is how black auto-formats our long Spark commands
# # W605 doesn't allow `\d` escape sequences but they are useful in regex (where they are not actually escape sequences)
# # E712 requires alternative syntax for conditionals that isn't Spark compatible
# # E731 does not allow for lambda expressions
